{% set name = "django-cognito-jwt" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 567418f170dc15f690a66cf3a7a934aed4f08f22bbb3090c99e15c6966198552

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.11
    - cryptography
    - djangorestframework
    - pyjwt
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - django_cognito_jwt

about:
  home: https://github.com/labd/django-cognito-jwt
  license: MIT
  license_family: MIT
  # https://github.com/labd/django-cognito-jwt/issues/31
  license_file: LICENSE
  summary: An Authentication backend for Django Rest Framework for AWS Cognito JWT tokens

extra:
  recipe-maintainers:
    - hadim
    - MichelML
